name: pnMarket
version: '${version}'
main: ru.privatenull.PnMarketPlugin
api-version: '1.16'
authors: [ privatenull ]
description: pnMarket - AuctionPlugin
website: https://github.com/Dy6HiLa/pnMarket
depend: [Vault]
softdepend: [PlayerPoints]
commands:
  dah:
    description: Команда для открытия аукциона pnMarket
  ah:
    description: Команда для открытия аукциона pnMarket
permissions:
  pnmarket.admin:
    description: Получать уведомления об обновлениях pnMarket
    default: op
